apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pixel-client-ingress
  namespace: pixel
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: $uri
spec:
  rules:
  - host: pixelclient.beniamindan.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pixel-client-service
            port:
              number: 80